---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: uploads
  label: Thumbnails
  create: documents
  match: "**/*"
- type: directory
  path: plugins
  label: Plugins
  create: documents
  match: "**/*.json"
  new_doc_ext: json
upload_dir: uploads
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
